#pragma once

#include <vector>
#include <string>

enum STATE_TYPE
{
	BOMBBOOM,
	BOMBIDLE,
	BOOMMOVE,
	BOSS1ATTACK,
	BOSS1ATTACK2,
	BOSS1ATTACK3,
	BOSS1DEAD,
	BOSS1IDLE,
	BOSS1IDLE2,
	BOSS1NONE,
	MONSTER1DEAD,
	MONSTER2ATTACK,
	MONSTER2DEAD,
	MONSTER2HIT,
	MONSTER2IDLE,
	MONSTER3ATTACK,
	MONSTER3DEAD,
	MONSTER3HIT,
	MONSTER3IDLE,
	MONSTERATTACK,
	MONSTERHIT,
	MONSTERIDLE,
	MONSTERRUN,
	NPCENTER_D1,
	NPCENTER_D2,
	NPCENTER_D3,
	NPCTEMD1,
	NPCTEMD2,
	NPCTEMD3,
	NPCTOWN1_D1,
	NPCTOWN1_D2,
	NPCTOWN1_D3,
	PAUSEMAIN,
	PAUSEMEMO,
	PAUSEOPTION,
	PLAYERATTACK1,
	PLAYERATTACK2,
	PLAYERATTACK3,
	PLAYERBRAKE,
	PLAYERHITSTATE,
	PLAYERIDLE,
	PLAYERIDLETORUN,
	PLAYERJUMPDOWN,
	PLAYERJUMPUP,
	PLAYERLAND,
	PLAYERROLL,
	PLAYERRUN,
	QUAKEEFFECT,
	QUAKEEFFECTNONE,
};

using namespace std;

class CState;

class CStateMgr
{
public:
	static void GetStateInfo(vector<wstring>& _vec);
	static CState * GetState(const wstring& _strStateName);
	static CState * GetState(UINT _iStateType);
	static const wchar_t * GetStateName(CState * _pState);
};
