#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	BGBELLRING,
	BGMOVE,
	BOSS1HIT,
	BOSS1HPCONTROLL,
	BOSS1HPEFFECT,
	BOSS1SCRIPT,
	BOSS1SETTARGET,
	BOSSSTAGESCRIPT,
	CAMERASCRIPT,
	CEILINGCHECK,
	CHANGESTAGE,
	COPYRIGHT,
	DOROMOVE,
	FONTPOS,
	GROUNDBOARD,
	GROUNDFIX,
	GROUNDSCRIPT,
	GROUNDSLOPE,
	GROUNDWALL,
	HPCONTROLL,
	HPREDUCEFX,
	HPRESTORE,
	JELLYJUMP,
	MISSILESCRIPT,
	MONSTER1HIT,
	MONSTER1SCRIPT,
	MONSTER2HITSCRIPT,
	MONSTER2SCRIPT,
	MONSTER2TARGET,
	MONSTER3HITSCRIPT,
	MONSTER3SCRIPT,
	MONSTER3SETTARGET,
	MONSTERSETTARGET,
	MPCONTROLL,
	NPCENTERDIALOG,
	NPCTEMPLE,
	NPCTEMPLEDIALOG,
	NPCTOWNDIALOG,
	PARTICLELEAF,
	PAUSEFONT,
	PLAYBUTTONSCRIPT,
	PLAYERATTACKSCRIPT,
	PLAYERHIT,
	PLAYERSCRIPT,
	WATERSPLASH,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
